### ISSUE TITLE
Fatal error when Woocommerce order marked completed.

### ISSUE THREAD

**Issue by luxwarp** [hizzle-co/noptin#613]
**Describe the bug**
When marking a Woocommerce order as Completed i get the following error. However the order gets the status completed even if you get this error.

```
2023-05-10T07:12:56+00:00 CRITICAL Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid
callback, cannot access protected method Noptin_WooCommerce_Product_Purchased_Trigger::maybe_trigger() in
/home/public_html/wp-includes/class-wp-hook.php:310

Stack trace:
#0 /home/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#1 /home/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#2 /home/public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(387): do_action()
#3 /home/public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(245): WC_Order->status_transition()
#4 /home/public_html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php(699): WC_Order->save()
#5 /home/public_html/wp-includes/class-wp-hook.php(310): WC_Meta_Box_Order_Data::save()
#6 /home/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#7 /home/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /home/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-meta-boxes.php(258): do_action()
#9 /home/public_html/wp-includes/class-wp-hook.php(310): WC_Admin_Meta_Boxes->save_meta_boxes()
#10 /home/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#11 /home/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#12 /home/public_html/wp-includes/post.php(4715): do_action()
#13 /home/public_html/wp-includes/post.php(4817): wp_insert_post()
#14 /home/public_html/wp-admin/includes/post.php(439): wp_update_post()
#15 /home/public_html/wp-admin/post.php(227): edit_post()
#16 {main}
  thrown i /home/public_html/wp-includes/class-wp-hook.php på rad 310
```

**To Reproduce**
1. Go to an woocommerce order 
2. Change status from whatever to Completed.
3. Save/Update order

**Expected behavior**
No error should appear and the order page should reload with the new status.

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Version

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser any

Using Wordpress 6.2, Woocommerce 7.7.0, Noptin 1.12.0

**Comment by luxwarp** [comment]
Solution is posted here https://wordpress.org/support/topic/fatal-error-in-php-8-1-2/#post-16732064 by [studiowoo](https://wordpress.org/support/users/studiowoo/)

>it can be fixed by changing the method on line 66 in 
```“wp-content/plugins/newsletter-optin-box/includes/automation-rules/triggers/class-noptin-woocommerce-product-purchased-trigger.php”```
>(maybe_trigger) from protected to public.

I tried it on my install and it worked perfectly!

**Comment by luxwarp** [comment]
Solved in latest update.
