### ISSUE TITLE
Fatal error upon confirming subscription from email link.

### ISSUE THREAD

**Issue by repomic** [hizzle-co/noptin#626]
### Description

URL in e-mail: https://[hostname]/?noptin_ns=confirm&nv={hash}

```
Fatal error:
Uncaught TypeError: array_merge(): Argument #1 must be of type array, stdClass given in ../wp-content/plugins/newsletter-optin-box/vendor/hizzle/store/src/Collection.php:754

Stack trace:
#0 ../wp-content/plugins/newsletter-optin-box/vendor/hizzle/store/src/Collection.php(754): array_merge(Object(stdClass), Array)
#1 ../wp-content/plugins/newsletter-optin-box/vendor/hizzle/store/src/Record.php(121): Hizzle\Store\Collection->read(Object(Hizzle\Noptin\DB\Automation_Rule))
#2 ../wp-content/plugins/newsletter-optin-box/vendor/hizzle/store/src/Collection.php(530): Hizzle\Store\Record->__construct('1', Array)
#3 ../wp-content/plugins/newsletter-optin-box/src/DB/Main.php(146): Hizzle\Store\Collection->get('1')
#4 ../wp-content/plugins/newsletter-optin-box/includes/functions.php(2034): Hizzle\Noptin\DB\Main->get('1', 'automation_rule...')
#5 ../wp-content/plugins/newsletter-optin-box/includes/emails/automated-email-types/class-type-automation-rule.php(221): noptin_get_automation_rule('1')
#6 ../wp-includes/class-wp-hook.php(308): Noptin_Automation_Rule_Email->maybe_send_notification(Array, Object(Noptin_Automated_Email))
#7 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#8 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#9 ../wp-content/plugins/newsletter-optin-box/includes/automation-rules/actions/class-noptin-email-action.php(116): do_action('noptin_send_aut...', Array, Object(Noptin_Automated_Email))
#10 ../wp-content/plugins/newsletter-optin-box/includes/automation-rules/actions/class-noptin-abstract-action.php(84): Noptin_Email_Action->run(Object(Noptin_Subscriber), Object(Noptin_Automation_Rule), Array)
#11 ../wp-content/plugins/newsletter-optin-box/includes/automation-rules/triggers/class-noptin-new-subscriber-trigger.php(205): Noptin_Abstract_Action->maybe_run(Object(Noptin_Subscriber), Object(Noptin_Automation_Rule), Array)
#12 ../wp-content/plugins/newsletter-optin-box/includes/automation-rules/triggers/class-noptin-new-subscriber-trigger.php(149): Noptin_New_Subscriber_Trigger->trigger(Object(Noptin_Subscriber), Array)
#13 ../wp-includes/class-wp-hook.php(308): Noptin_New_Subscriber_Trigger->maybe_trigger(Object(Noptin_Subscriber))
#14 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#15 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#16 ../wp-content/plugins/newsletter-optin-box/includes/subscriber.php(513): do_action('noptin_subscrib...', Object(Noptin_Subscriber))
#17 ../wp-content/plugins/newsletter-optin-box/includes/class-noptin-page.php(496): confirm_noptin_subscriber_email(Object(Noptin_Subscriber))
#18 ../wp-includes/class-wp-hook.php(308): Noptin_Page->pre_confirm_subscription('')
#19 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#20 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#21 ../wp-content/plugins/newsletter-optin-box/includes/class-noptin-page.php(622): do_action('noptin_pre_page...', '')
#22 ../wp-includes/class-wp-hook.php(308): Noptin_Page->load_actions_page('')
#23 ../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#24 ../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#25 ../wp-includes/template-loader.php(13): do_action('template_redire...')
#26 ../wp-blog-header.php(19): require_once('/home/www/boate...')
#27 ../index.php(17): require('/home/www/boate...')
#28 {main} thrown in ../wp-content/plugins/newsletter-optin-box/vendor/hizzle/store/src/Collection.php on line 754
```

**Comment by picocodes** [comment]
Hi, could you try emptying your object cache then let me know if the issue still exists.

**Comment by repomic** [comment]
Tried clearing all cache within w3 total cache. No change. Same Error.

**Comment by picocodes** [comment]
Closing as fixed
